### ISSUE TITLE
Role synchronization not working properly for given dotcms.saml.include.roles.pattern filter

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-dotcms-openSAML3#21]
Roles are not being set properly even when the filter defined in dotcms.saml.include.roles.pattern is returning groups from the IdP.

Related to: https://my.dotcms.com/tickets/detail.dot?id=3464c566-5d7f-4d09-84b7-6b402d31768a

**Comment by jdotcms** [comment]
First thing we have to see what is coming from SAML response (the roles) and which patterns are we using (there are being logged)
We need to log some stuff, first thing we have to make sure the user is active, otherwise not any role will be apply.
We have also to check the logs, to see if we are or not skipping the user roles, there are logs also when the role is add.

For reference see the class:
OpenSamlAuthenticationServiceImpl.addRoles

**Comment by jtesser** [comment]
Also and it is probably not this do make sure the role_keys are what u think they are.

**Comment by gabbydotCMS** [comment]
We were indeed getting all the information we needed in the assertion, and the roles were properly configured.

The issue was in this method: 
https://github.com/dotCMS/plugin-dotcms-openSAML3/blob/master/src/com/dotcms/plugin/saml/v3/OpenSamlAuthenticationServiceImpl.java#L265

We needed to compare field names against attribute.getFriendlyName() instead of attribute.getName() .
